name: LeonCSAddon
version: '${project.version}'
main: net.azisaba.leoncsaddon.LeonCSAddon
api-version: '1.16'
depend:
  - CrackShot
commands:
  randomdamage:
    permission: leoncsaddon.command.admin
    aliases: [rd]
permissions:
  leoncsaddon.command.admin:
    default: op